# Generated by Django 4.0.5 on 2022-06-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buseiness',
            name='neighbourhood',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='neighbourhood',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='neighbourhood',
            field=models.CharField(max_length=300),
        ),
    ]
